### ISSUE TITLE
When zooming out to max, black bar appears on the right

### ISSUE THREAD

**Issue by Rebeckatje** [thespbgamer/ZoomLevel#7] opened 2021-05-20 10:54 UTC
smapi log 64 bit: https://smapi.io/log/e61615ed884348838787a5ce840621dc
If I update from 1.5.2 to any other recent version of spacecore, it still happens.

When zooming out to the max with the comma hotkey, with the standard config that gets created when running the game once, a black bar/square appears in the area which is supposed to be shown. Always only on the right side. It happens everywhere, for example where Marnie's house is with the river, the town and also in modded locations such as (example) the Deep Woods.

Stardew Valley version is 64 bit.
Problem happens when in Fullscreen, Windowed and Windowed Borderless. My resolution in-game is 1920x1080. If I am in Windowed mode and I make the window 'small', as in, not taking up the whole screen (except taskbar), then I don't see the black bar.
I tested some other resolutions, it only happens in 1600x900, 1680x1050 and 1920x1080 for me.
Images: https://imgur.com/a/9Jw2WV5

Edit: If I reset the zoom with the Home button and then zoom out 11 times, on the 11th is shows the black bar and gets bigger the more I zoom out.

**Comment by thespbgamer** [comment] 2021-05-20 13:16
That is most likely a mod compatibility problem, in stardew valley 1.5 all zoom functions changed because of local co-op, so I can't fix the problem because it's a codding on other mods (most likely).
And I know, for example, UI info Suite had that problem and it was fixed by someone (can't remember who) and know exists a forked UI info Suite with that issue fixed.
Sorry, I can't give more help than that but's it's really out of my expertise.
I will try more stuff to see if the problem is not mine, if you don't see an update on this mod soon then I could not find any problem.

**Closed by thespbgamer** 2021-05-20 13:16 UTC
