### ISSUE TITLE
UI problem with mod "Numerical Health"

### ISSUE THREAD

**Issue by HeroWillHD** [thespbgamer/ZoomLevel#11] opened 2022-12-20 19:10 UTC
Hello there! The mod "Numerical Health" (https://www.nexusmods.com/stardewvalley/mods/4863) adds numerical energy and health to the game interface (as the name says), and there's a keybind to reposition it anywhere on the screen while in-game (can also configure manualy with screen coordinates on config file). The problem is that after i installed ZoomLevel, the numerical interface of that said mod isn't staying in the same place as i point it with my mouse+keybind. I can still position it where i want to, but it's kind of a hassle because i need to keep pressing the keybind in order to align where i want to.
Anyway, even if you can't or don't want to address this issue, thank you very much for the mod and happy holidays!

**Comment by thespbgamer** [comment] 2022-12-20 19:14
Well, at the moment I can't see this, but when I get the time, i'll check it out, might take months though.

**Comment by thespbgamer** [comment] 2023-01-21 19:47
It seams that the problem is with the Numerical Health mod, tried a few stuff, but yeah, the other mod needs an update, until then, I'll close this issue unless some information changes.

**Closed by thespbgamer** 2023-01-21 19:47 UTC
Labels: enhancement
