### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by geenaxion** [thespbgamer/ZoomLevel#14] opened 2023-02-01 20:40 UTC
1st 
![20230202042703_1](https://user-images.githubusercontent.com/10777018/216157779-d8b400e9-f952-4e5b-96dd-eb3293df9635.jpg)

I think it might have something to do with the camera as im unable to move the camera to the right side when on the museum trying to donate.
only way to this on this issue is to zoom out so i can see all of the available area to place the items.
also I think this is related when there is a heart even on going the camera is acting strange like its not focusing on the right location.

2nd 
![20230202042909_1](https://user-images.githubusercontent.com/10777018/216157796-e3841a3d-4c53-42d5-8d37-2ea88d61b9d6.jpg)

I tried the auto zoom to map size, i cant go back to the previous state since UI is not showing up.

**Comment by geenaxion** [comment] 2023-02-01 20:42
Just additional info on the 2nd issue. i tried pressing the hotkey i set the zoom in but it wont work.

**Comment by thespbgamer** [comment] 2023-02-01 20:46
Can you tell me what settings do you have, it would be easier for me to find the bugs that way, gonna test those issues now, but if you can tell me the settings, that would help a lot

**Comment by geenaxion** [comment] 2023-02-01 20:54
i reverted back to the previous version but this is the settings im using.

![20230202045217_1](https://user-images.githubusercontent.com/10777018/216160886-7ee11723-9cf5-4667-9518-fa5e4ef3c541.jpg)

btw, theres no error in smapi when this occured.

**Comment by thespbgamer** [comment] 2023-02-01 21:25
![000](https://user-images.githubusercontent.com/30112696/216166518-d50078c4-cc20-43d2-8928-0242b6706637.png)

These are my settings, and tried to recreate both of the bugs and did not had any issues, is it possible for you to give any more info, because i'm not able to recreate the bugs.

**Comment by geenaxion** [comment] 2023-02-01 21:55
Im not able to recreate the 2nd issue. must have been random.

but i tried going to the museum to try and donate.  I still cant scroll to the right side of the screen. 
only way to see is to zoom out.

![20230202055200_1](https://user-images.githubusercontent.com/10777018/216172068-801fba56-2ec4-4f94-b6ac-f95ff1543e22.jpg)

![20230202055235_1](https://user-images.githubusercontent.com/10777018/216172105-123581a2-d355-4409-8010-91740ef8b1f8.jpg)

**Comment by geenaxion** [comment] 2023-02-01 22:15
Yes, i revert back to 1.14.0
it doesnt occur.

here, if it will help.
https://smapi.io/log/902cf9efb5ab4af59eb731060831b86e

**Comment by thespbgamer** [comment] 2023-02-01 22:18
I see, well it must be something the the camera, can't recreate the bug, will try to fix this, might take a while since I  have a lot to check

**Comment by thespbgamer** [comment] 2023-02-01 22:22
A few questions that might help me look for the bug
• Do you move the camera, after or during the donation, or only before?
• Do you move the camera before entering the museum ?

**Comment by thespbgamer** [comment] 2023-02-01 22:26
Another thing. the mod that changes the museum map, what is it called, might be an issue there. @geenaxion

**Comment by geenaxion** [comment] 2023-02-01 22:34
I didnt move the camera after entering the museum.
I also noticed that there's an automatic camera movement before i get to scroll.

This camera movement is new to the latest version? i havent used that yet.
I'm only using the zoom in and zoom out function.

**Comment by geenaxion** [comment] 2023-02-01 22:36
I'm not exactly sure but I think the museum changes is related to Stardew Valley Expanded, since i don't have any museum mod installed.

**Comment by geenaxion** [comment] 2023-02-01 22:37
or maybe the NPC Jasper mod. 
I think that mod does change somethings on the museum. i'll take a look

**Comment by thespbgamer** [comment] 2023-02-01 22:38
> I didnt move the camera after entering the museum. I also noticed that there's an automatic camera movement before i get to scroll.
> 
> This camera movement is new to the latest version? i havent used that yet. I'm only using the zoom in and zoom out function.

Yeah, 2.0.0 feature, might be broken with some mod, but I have to check that better tomorrow, in the vanilla map, it has no issue

**Comment by geenaxion** [comment] 2023-02-01 22:39
Yeah i think this is the one that changes the musuem.
https://www.nexusmods.com/stardewvalley/mods/5599?tab=description

**Comment by thespbgamer** [comment] 2023-02-02 09:58
> Yeah i think this is the one that changes the musuem. https://www.nexusmods.com/stardewvalley/mods/5599?tab=description

It was indeed a problem with this mod, fixing this right now, update might be released today

**Comment by thespbgamer** [comment] 2023-02-02 10:23
@geenaxion Please tell me if the issue is fixed, I want to know if I can close this issue or not, should be fixed in 2.0.1

**Comment by geenaxion** [comment] 2023-02-02 11:05
I can confirm that the issue is fixed.
Thank you

**Closed** 2023-02-02 11:19 UTC
Labels: bug
